name: 'retailpulse'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pandas=1.5.3 
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - plotly=5.11.0
  - dash=2.7.0
  - jupyterlab=3.5.2
  - pip=22.3.1
  - pip:
    - flask==2.2.2
    - gunicorn==20.1.0
