name: 'retailpulse'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - dash=2.7.0
  - altair=5.5.0
  - pandas=1.5.3 
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - plotly=5.11.0
  - jupyterlab=3.5.2
  - pip=22.3.1
  - openpyxl
  - narwhals>=1.14.2
  - pyarrow==19.0.1
  - pip:
    - werkzeug==2.0.3
    - dash-vega-components==0.11.0
    - dash-bootstrap-components
    - pytest==8.3.5
